baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Hugo cocorico"
theme = "coco"
author = "Shurikken"
copyright = "Copyright Â© 2020, Shurrikken, all rights reserved."
summaryLength =  "20"




# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
    name = "Cocorico"
    description = "Web site of cocorico"
    author = "Shurikken"
    authorimage = "../../imageauthor.jpg"
    Featured_image= "../../bean.jpg"
    github_user = "Shurikken"
    github_repo = ""
    github_banner = true
    favicon = "favicon.ico"
